security:
  oauth2:
    client:
      # From OIDC app
      clientId:  # clientId
      clientSecret:  #clientSecret
      # From Authorization Server's metadata
      accessTokenUri: https://prdemo.oktapreview.com/oauth2/ausb56f72xY0INs860h7/v1/token # token_endpoint
      userAuthorizationUri: https://prdemo.oktapreview.com/oauth2/ausb56f72xY0INs860h7/v1/authorize # authorization_endpoint
      clientAuthenticationScheme: form
      scope: openid email profile  phone  offline_access
      #RedirectUri: http://localhost:8080/

    resource:
      # from your Auth Server's metadata, check .well-known/openid-configuration
      # if not in .well-known/oauth-authorization-server
      userInfoUri: https://prdemo.oktapreview.com/oauth2/ausb56f72xY0INs860h7/v1/userinfo # userinfo_endpoint
      preferTokenInfo: false
      openIdConfigUri: https://prdemo.oktapreview.com/oauth2/ausb56f72xY0INs860h7/.well-known/oauth-authorization-server

okta:
  tenant:
    uri:  https://prdemo.oktapreview.com/ #https://your-tenant.oktapreview.com
  moreSecure:
    authorities: employeeAdmin, employeeUser # comma separated list of groups that should have access to the /more-secure endpoint

logging:
  level:
    ROOT: INFO

spring:
  cache:
    ehcache:
      config: classpath:ehcache.xml


