
okta:
  oauth:
    baseUrl: https://prdemo.oktapreview.com/
    issuer: https://prdemo.oktapreview.com/oauth2/ausca4x6gjdoZn9u60h7
    audience: TISensorAPI
    clientId: 0oacclsuc1Qmhepm90h7
    rolesClaim: groups
    redirectUri:  http://localhost:8080/dashboard.html


logging:
  level:
    ROOT: DEBUG
