package com.okta.poc.iot.tisensor.apidynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import org.springframework.stereotype.Repository;


@DynamoDBTable(tableName = "AccelerometerData")
@Repository
public class AccelerometerDataModel {

    String id;
    XYZModel accData;
    long dataCaptureTime;
    String deviceID;
    String userID;

    @DynamoDBAttribute
    public String getUserID() {
        return userID;
    }
    public void setUserID(String userID) {
        this.userID = userID;
    }


    @DynamoDBAttribute
    public String getDeviceID() {
        return deviceID;
    }
    public void setDeviceID(String deviceID) {
        this.deviceID = deviceID;
    }

    //@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName="Id")
    public String getId() {
        return id;
    }
    public void setId(String id){ this.id = id;}

    public AccelerometerDataModel() { }
    public AccelerometerDataModel(String userID, String deviceID){
        this.userID = userID;
        this.deviceID = deviceID;
    }

    @DynamoDBAttribute
    public XYZModel getAccData() {
        return accData;
    }
    public void setAccData(XYZModel accData) {
        this.accData = accData;
    }

    public void setDataCaptureTime(long dataCaptureTime) {
        this.dataCaptureTime = dataCaptureTime;
    }
    @DynamoDBAttribute
    public long getDataCaptureTime() {
        return dataCaptureTime;
    }
}
