package com.okta.poc.iot.tisensor.apidynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import org.socialsignin.spring.data.dynamodb.repository.EnableScan;
import org.springframework.stereotype.Repository;


@DynamoDBTable(tableName = "GyroscopeData")
@Repository
@EnableScan
//@EnableDynamoDBRepositories
public class GyroscopeDataModel {

    String Id;
    XYZModel gyroData;
    long dataCaptureTime;
    String deviceID;
    String userID;
 //   static final long dataCaptureIdx = 0L;

    @DynamoDBAttribute
    public String getUserID() {
        return userID;
    }
    public void setUserID(String userID) {
        this.userID = userID;
    }


    @DynamoDBAttribute
    public String getDeviceID() {
        return deviceID;
    }
    public void setDeviceID(String deviceID) {
        this.deviceID = deviceID;
    }

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey
    //@DynamoDBHashKey(attributeName="Id")
    public String getId() {
        return Id;
    }
    public void setId(String id){ this.Id = id;}

    public GyroscopeDataModel() { }
    public GyroscopeDataModel(String userID, String deviceID){
        this.userID = userID;
        this.deviceID = deviceID;
    }

    //
    @DynamoDBAttribute
    public XYZModel getGyroData() {
        return gyroData;
    }
    public void setGyroData(XYZModel gyroData) {
        this.gyroData = gyroData;
    }


    @DynamoDBAttribute
    //@DynamoDBIndexRangeKey(localSecondaryIndexName =
    //        "dataCaptureTimeIdx")
    //@DynamoDBRangeKey(attributeName="dataCaptureTimeIdx")
    public long getDataCaptureTime() {
        return dataCaptureTime;
    }
    public void setDataCaptureTime(long dataCaptureTime) {
        this.dataCaptureTime = dataCaptureTime;
    }



    @Override
    public String toString() {
        return "GyroscopeDataModel{" +
                "id='" + Id + '\'' +
                ", gyroData=" + gyroData.toString() +
                ", dataCaptureTime=" + dataCaptureTime +
                ", deviceID='" + deviceID + '\'' +
                ", userID='" + userID + '\'' +
                '}';
    }
}
