package com.okta.poc.iot.tisensor.apidynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import org.springframework.stereotype.Repository;

@DynamoDBTable(tableName = "ProductInfo")
@Repository
public class ProductInfo {


    private Integer id;
    private String msrp;
    private String cost;

    @DynamoDBHashKey
  //  @DynamoDBAutoGeneratedKey
    public Integer getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getMsrp() {
        return msrp;
    }

    @DynamoDBAttribute
    public String getCost() {
        return cost;
    }

    public ProductInfo(){}
    public ProductInfo(String expectedCost, String expectedPrice){

    }

    public ProductInfo(Integer id, String msrp, String cost) {
        this.id = id;
        this.msrp = msrp;
        this.cost = cost;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public void setMsrp(String msrp) {
        this.msrp = msrp;
    }

    public void setCost(String cost) {
        this.cost = cost;
    }
}