package com.okta.poc.iot.tisensor.apidynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import org.springframework.stereotype.Repository;

@DynamoDBTable(tableName = "UserModel")
@Repository
public class UserModel {


    private String id;
    private String userID;
    private String deviceID;
    private String userName;


    public long getCheckinTime() {
        return checkinTime;
    }

    public void setCheckinTime(long checkinTime) {
        this.checkinTime = checkinTime;
    }

    private long checkinTime;

    @DynamoDBHashKey
   @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

   // @DynamoDBKeyed(value = KeyType.HASH)
    @DynamoDBAttribute
    //@DynamoDBIndexHashKey(globalSecondaryIndexName = "userIDX",attributeName = "userID")
    public String getUserID() {
        return userID;
    }

    //@DynamoDBIndexHashKey(globalSecondaryIndexName = "deviceIDX",attributeName = "deviceID")
    @DynamoDBAttribute
    public String getDeviceID() {
        return deviceID;
    }

    @DynamoDBAttribute
    public String getUserName(){ return userName;}
    public void setUserName(String userName) {
        this.userName = userName;
    }

    public UserModel(){}

    public UserModel(String userID, String deviceID,long checkinTime, String userName){
        this.userID = userID;
        this.deviceID = deviceID;
        this.checkinTime = checkinTime;
        this.userName = userName;
    }

    public UserModel(String id, String userID, String deviceID, long checkinTime) {
        this.id = id;
        this.userID = userID;
        this.deviceID = deviceID;
        this.checkinTime = checkinTime;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    public void setDeviceID(String deviceID) {
        this.deviceID = deviceID;
    }

    @Override
    public String toString() {
        return "UserModel{" +
                "id='" + id + '\'' +
                ", userID='" + userID + '\'' +
                ", deviceID='" + deviceID + '\'' +
                '}';
    }
}